
# Herdar configurações do rubocop-rails-omakase
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - '.git/**/*'
    - 'spec/fixtures/**/*'

# RSpec configs adicionais (não incluídas no omakase)
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

RSpec/LetSetup:
  Enabled: false

RSpec/ContextWording:
  Enabled: true
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for

# Ajustes específicos (estas configurações sobrescrevem o omakase)
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/**/*'

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false