development:
  adapter: async
  channel_prefix: bookclub_development

test:
  adapter: test
  channel_prefix: bookclub_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379/1" } %>
  channel_prefix: bookclub_production
